import * as anchor from "@coral-xyz/anchor";
import { Program } from "@coral-xyz/anchor";
import { PublicKey, Keypair, SystemProgram } from "@solana/web3.js";
import { assert } from "chai";

// These types will be generated by `anchor build`
// import { HolancPool } from "../target/types/holanc_pool";
// import { HolancVerifier } from "../target/types/holanc_verifier";
// import { HolancNullifier } from "../target/types/holanc_nullifier";
// import { HolancBridge } from "../target/types/holanc_bridge";
// import { HolancCompliance } from "../target/types/holanc_compliance";

describe("holanc", () => {
  const provider = anchor.AnchorProvider.env();
  anchor.setProvider(provider);

  // Program IDs (must match Anchor.toml)
  const POOL_ID = new PublicKey("6fhYW9wEHD3yCdvfyBCg3jxVB7sWVmqNgQyvMwSFi1GT");
  const VERIFIER_ID = new PublicKey(
    "GmkUhTQ5LKxRFfwEhJTGYpsBE8Y7mMBpfqwe7mX71Gpi",
  );
  const NULLIFIER_ID = new PublicKey(
    "BbcPjKizadFZb55MSFcg1q2MxAbnSbnvKvorTXutK3Si",
  );
  const BRIDGE_ID = new PublicKey(
    "H14juazDyYfTD4PT2oiBoLoHPKcWy4v6jggyNXJNG91K",
  );
  const COMPLIANCE_ID = new PublicKey(
    "8QKUprH8TMiffMga7tVJZ6qtvwZogmz9SibDswCWKnHE",
  );

  describe("smoke tests", () => {
    it("programs are deployed at expected addresses", async () => {
      // Verify program accounts exist on-chain after deployment
      const poolInfo = await provider.connection.getAccountInfo(POOL_ID);
      const verifierInfo = await provider.connection.getAccountInfo(
        VERIFIER_ID,
      );
      const nullifierInfo = await provider.connection.getAccountInfo(
        NULLIFIER_ID,
      );
      const bridgeInfo = await provider.connection.getAccountInfo(BRIDGE_ID);
      const complianceInfo = await provider.connection.getAccountInfo(
        COMPLIANCE_ID,
      );

      // In localnet with `anchor test`, these should be executable
      assert.isNotNull(poolInfo, "Pool program not found");
      assert.isNotNull(verifierInfo, "Verifier program not found");
      assert.isNotNull(nullifierInfo, "Nullifier program not found");
      assert.isNotNull(bridgeInfo, "Bridge program not found");
      assert.isNotNull(complianceInfo, "Compliance program not found");
    });
  });

  // Additional integration tests will be added after `anchor build` generates IDL types.
  // See tests/anchor/ for program-specific tests.
  // See tests/e2e/ for SDK-level tests.
  // See tests/circuits/ for circuit structure tests.
});
