/**
 * Pool program instruction tests.
 *
 * Tests pool initialization, deposit, transfer, and withdraw instructions
 * against a local Anchor validator. Run via `anchor test`.
 */

import * as anchor from "@coral-xyz/anchor";
import { Program, BN } from "@coral-xyz/anchor";
import {
  PublicKey,
  Keypair,
  SystemProgram,
  LAMPORTS_PER_SOL,
} from "@solana/web3.js";
import {
  TOKEN_PROGRAM_ID,
  createMint,
  createAccount,
  mintTo,
  getAccount,
} from "@solana/spl-token";
import { assert } from "chai";

const POOL_ID = new PublicKey("6fhYW9wEHD3yCdvfyBCg3jxVB7sWVmqNgQyvMwSFi1GT");

describe("holanc-pool instructions", () => {
  const provider = anchor.AnchorProvider.env();
  anchor.setProvider(provider);

  const payer = (provider.wallet as anchor.Wallet).payer;
  let tokenMint: PublicKey;
  let poolPda: PublicKey;
  let poolBump: number;
  let vaultPda: PublicKey;
  let vaultBump: number;
  let vaultAuthPda: PublicKey;
  let vaultAuthBump: number;
  let depositorAta: PublicKey;
  let nullifierRegistry: Keypair;

  // We'll use the pool IDL (generated by anchor build)
  let poolProgram: Program;

  before(async () => {
    // Load IDL-based program — falls back to raw instruction building if IDL not available
    try {
      const idl = await Program.fetchIdl(POOL_ID, provider);
      if (idl) {
        poolProgram = new Program(idl, provider);
      }
    } catch {
      // IDL may not be deployed; tests below use raw instruction building as fallback
    }

    // Create a token mint
    tokenMint = await createMint(
      provider.connection,
      payer,
      payer.publicKey,
      null,
      9, // 9 decimals
    );

    // Derive PDAs
    [poolPda, poolBump] = PublicKey.findProgramAddressSync(
      [Buffer.from("pool"), tokenMint.toBuffer()],
      POOL_ID,
    );

    [vaultPda, vaultBump] = PublicKey.findProgramAddressSync(
      [Buffer.from("vault"), poolPda.toBuffer()],
      POOL_ID,
    );

    [vaultAuthPda, vaultAuthBump] = PublicKey.findProgramAddressSync(
      [Buffer.from("vault_auth"), poolPda.toBuffer()],
      POOL_ID,
    );

    // Create depositor's token account and fund it
    depositorAta = await createAccount(
      provider.connection,
      payer,
      tokenMint,
      payer.publicKey,
    );
    await mintTo(
      provider.connection,
      payer,
      tokenMint,
      depositorAta,
      payer,
      10_000_000_000, // 10 tokens
    );

    // Create a nullifier registry account
    nullifierRegistry = Keypair.generate();
  });

  describe("initialize", () => {
    it("initializes the pool with correct state", async () => {
      if (!poolProgram) {
        console.log(
          "⚠ Skipping: pool IDL not available (run anchor build first)",
        );
        return;
      }

      await poolProgram.methods
        .initialize(poolBump)
        .accounts({
          pool: poolPda,
          tokenMint,
          vault: vaultPda,
          vaultAuthority: vaultAuthPda,
          authority: payer.publicKey,
          tokenProgram: TOKEN_PROGRAM_ID,
          systemProgram: SystemProgram.programId,
          rent: anchor.web3.SYSVAR_RENT_PUBKEY,
        })
        .rpc();

      const poolAccount = await poolProgram.account.poolState.fetch(poolPda);
      assert.equal(
        poolAccount.authority.toBase58(),
        payer.publicKey.toBase58(),
      );
      assert.equal(poolAccount.tokenMint.toBase58(), tokenMint.toBase58());
      assert.equal(poolAccount.nextLeafIndex.toNumber(), 0);
      assert.equal(poolAccount.totalDeposited.toNumber(), 0);
      assert.isFalse(poolAccount.isPaused);
    });
  });

  describe("deposit", () => {
    it("deposits tokens and records commitment", async () => {
      if (!poolProgram) {
        console.log("⚠ Skipping: pool IDL not available");
        return;
      }

      const amount = new BN(1_000_000_000); // 1 token
      const commitment = Buffer.alloc(32);
      commitment[0] = 0xab; // Mock commitment
      const encryptedNote = Buffer.from("encrypted_note_data");

      const balanceBefore = (
        await getAccount(provider.connection, depositorAta)
      ).amount;

      await poolProgram.methods
        .deposit(amount, [...commitment], encryptedNote)
        .accounts({
          pool: poolPda,
          depositorTokenAccount: depositorAta,
          vault: vaultPda,
          depositor: payer.publicKey,
          tokenProgram: TOKEN_PROGRAM_ID,
        })
        .rpc();

      const balanceAfter = (await getAccount(provider.connection, depositorAta))
        .amount;
      assert.equal(
        BigInt(balanceBefore) - BigInt(balanceAfter),
        BigInt(1_000_000_000),
      );

      const poolAccount = await poolProgram.account.poolState.fetch(poolPda);
      assert.equal(poolAccount.nextLeafIndex.toNumber(), 1);
      assert.equal(poolAccount.totalDeposited.toNumber(), 1_000_000_000);
    });

    it("rejects zero amount deposit", async () => {
      if (!poolProgram) return;

      const commitment = Buffer.alloc(32);
      try {
        await poolProgram.methods
          .deposit(new BN(0), [...commitment], Buffer.alloc(0))
          .accounts({
            pool: poolPda,
            depositorTokenAccount: depositorAta,
            vault: vaultPda,
            depositor: payer.publicKey,
            tokenProgram: TOKEN_PROGRAM_ID,
          })
          .rpc();
        assert.fail("Should have thrown");
      } catch (err: any) {
        assert.include(err.toString(), "ZeroAmount");
      }
    });

    it("rejects oversized encrypted note", async () => {
      if (!poolProgram) return;

      const commitment = Buffer.alloc(32);
      const oversizedNote = Buffer.alloc(300); // > 256 limit
      try {
        await poolProgram.methods
          .deposit(new BN(1_000_000), [...commitment], oversizedNote)
          .accounts({
            pool: poolPda,
            depositorTokenAccount: depositorAta,
            vault: vaultPda,
            depositor: payer.publicKey,
            tokenProgram: TOKEN_PROGRAM_ID,
          })
          .rpc();
        assert.fail("Should have thrown");
      } catch (err: any) {
        assert.include(err.toString(), "EncryptedNoteTooLarge");
      }
    });
  });

  describe("update_root", () => {
    it("updates merkle root as authority", async () => {
      if (!poolProgram) return;

      const newRoot = Buffer.alloc(32);
      newRoot.fill(0xcc);

      await poolProgram.methods
        .updateRoot([...newRoot])
        .accounts({
          pool: poolPda,
          authority: payer.publicKey,
        })
        .rpc();

      const poolAccount = await poolProgram.account.poolState.fetch(poolPda);
      assert.deepEqual(Buffer.from(poolAccount.currentRoot), newRoot);
    });
  });

  describe("set_paused", () => {
    it("pauses and unpauses the pool", async () => {
      if (!poolProgram) return;

      // Pause
      await poolProgram.methods
        .setPaused(true)
        .accounts({
          pool: poolPda,
          authority: payer.publicKey,
        })
        .rpc();

      let poolAccount = await poolProgram.account.poolState.fetch(poolPda);
      assert.isTrue(poolAccount.isPaused);

      // Deposit should fail while paused
      const commitment = Buffer.alloc(32);
      try {
        await poolProgram.methods
          .deposit(new BN(1000), [...commitment], Buffer.alloc(0))
          .accounts({
            pool: poolPda,
            depositorTokenAccount: depositorAta,
            vault: vaultPda,
            depositor: payer.publicKey,
            tokenProgram: TOKEN_PROGRAM_ID,
          })
          .rpc();
        assert.fail("Should have thrown");
      } catch (err: any) {
        assert.include(err.toString(), "PoolPaused");
      }

      // Unpause
      await poolProgram.methods
        .setPaused(false)
        .accounts({
          pool: poolPda,
          authority: payer.publicKey,
        })
        .rpc();

      poolAccount = await poolProgram.account.poolState.fetch(poolPda);
      assert.isFalse(poolAccount.isPaused);
    });

    it("rejects unauthorized pause", async () => {
      if (!poolProgram) return;

      const badActor = Keypair.generate();
      // Fund the bad actor for tx fees
      const sig = await provider.connection.requestAirdrop(
        badActor.publicKey,
        LAMPORTS_PER_SOL,
      );
      await provider.connection.confirmTransaction(sig);

      try {
        await poolProgram.methods
          .setPaused(true)
          .accounts({
            pool: poolPda,
            authority: badActor.publicKey,
          })
          .signers([badActor])
          .rpc();
        assert.fail("Should have thrown");
      } catch (err: any) {
        assert.include(err.toString(), "Unauthorized");
      }
    });
  });
});
